// Auto-adapter CLI: generates a Declaro plugin wrapper for a React component.
// Usage: declaro adapt <react-package-name>

import { execSync } from "node:child_process"
import * as fs from "node:fs"
import * as path from "node:path"

export async function adaptCommand(args: string[]): Promise<void> {
  const pkgName = args[0]
  if (!pkgName) {
    console.error("Error: 请指定要适配的 React 组件包名")
    console.log("  declaro adapt react-datepicker")
    process.exit(1)
  }

  console.log(`\n🔧 Adapting ${pkgName} for Declaro...\n`)

  // Derive plugin name from package name
  const pluginName = `declaro-${pkgName.replace(/^@/, "").replace("/", "-").replace(/^react-/, "")}`

  // Check if already installed
  let installed = false
  try {
    execSync(`npm ls ${pkgName} --depth=0`, { stdio: "pipe" })
    installed = true
  } catch {
    console.log(`Installing ${pkgName}...`)
    try {
      execSync(`npm install ${pkgName}`, { stdio: "inherit" })
      installed = true
    } catch {
      console.error(`Failed to install ${pkgName}`)
      process.exit(1)
    }
  }

  // Generate plugin directory
  const pluginDir = path.resolve(process.cwd(), `declaro-plugins/${pluginName}`)
  if (fs.existsSync(pluginDir)) {
    console.log(`Plugin directory already exists: ${pluginDir}`)
  } else {
    fs.mkdirSync(pluginDir, { recursive: true })
    console.log(`  ✓ Created ${pluginDir}`)
  }

  // Generate index.ts
  const indexContent = `// Auto-generated Declaro plugin for ${pkgName}
// Generated by: declaro adapt ${pkgName}
//
// This wraps the React component as a Declaro ReactIsland.
// Import and use in your Declaro pages:
//
//   import { ${capitalize(pluginName.replace(/^declaro-/, ""))} } from "./declaro-plugins/${pluginName}"

import { ReactIsland } from "declaro"
import type { ReactIslandNode } from "declaro"

export type ${capitalize(pluginName.replace(/^declaro-/, ""))}Props = {
  id: string
  slot?: string
  order?: number
  /** Props forwarded to the underlying ${pkgName} component */
  props?: Record<string, unknown>
}

export function ${capitalize(pluginName.replace(/^declaro-/, ""))}(config: ${capitalize(pluginName.replace(/^declaro-/, ""))}Props): ReactIslandNode {
  return ReactIsland({
    id: config.id,
    component: "${pkgName}",
    props: config.props,
    slot: config.slot,
    order: config.order,
  })
}
`

  fs.writeFileSync(path.join(pluginDir, "index.ts"), indexContent)
  console.log(`  ✓ Generated index.ts`)

  // Generate package.json
  const pkgJson = {
    name: pluginName,
    version: "0.1.0",
    description: `Declaro plugin wrapping ${pkgName}`,
    main: "./index.ts",
    declaro: {
      components: [capitalize(pluginName.replace(/^declaro-/, ""))],
    },
    peerDependencies: {
      declaro: "*",
      [pkgName]: "*",
    },
  }

  fs.writeFileSync(path.join(pluginDir, "package.json"), JSON.stringify(pkgJson, null, 2))
  console.log(`  ✓ Generated package.json`)

  // Generate README
  const readme = `# ${pluginName}

Declaro plugin wrapping [${pkgName}](https://www.npmjs.com/package/${pkgName}).

## Usage

\`\`\`ts
import { ${capitalize(pluginName.replace(/^declaro-/, ""))} } from "./declaro-plugins/${pluginName}"

Page({
  children: [
    ${capitalize(pluginName.replace(/^declaro-/, ""))}({
      id: "my-${pluginName.replace(/^declaro-/, "")}",
      props: { /* ${pkgName} props */ },
    }),
  ],
})
\`\`\`

Generated by \`declaro adapt ${pkgName}\`.
`

  fs.writeFileSync(path.join(pluginDir, "README.md"), readme)
  console.log(`  ✓ Generated README.md`)

  console.log(`\n✅ Plugin generated: ${pluginDir}`)
  console.log(`\nTo use it, import in your page:`)
  console.log(`  import { ${capitalize(pluginName.replace(/^declaro-/, ""))} } from "./declaro-plugins/${pluginName}"`)
  console.log(`\nMake sure to load React in your page head:`)
  console.log(`  Script({ src: "https://unpkg.com/react@18/umd/react.production.min.js" })`)
  console.log(`  Script({ src: "https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" })`)
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/[-_]([a-z])/g, (_, c) => c.toUpperCase())
}
