// Declaro deploy command (Phase 4).
// Compiles all pages, bundles the server, and generates
// platform-specific deployment configurations.

import * as fs from "node:fs"
import * as path from "node:path"
import { compilePage } from "../compiler/compile"
import type { PageNode } from "../dsl"

export type DeployTarget = "node" | "vercel" | "cloudflare"

export interface DeployOptions {
  target: DeployTarget
  outDir: string
  projectName: string
}

interface DeployAdapter {
  name: string
  generate(outputDir: string, routes: Array<{ path: string; label: string }>): Promise<void>
}

/**
 * Main deploy entry point.
 */
export async function deploy(options: DeployOptions): Promise<void> {
  const { target, outDir, projectName } = options

  console.log(`\n🚀 Declaro Deploy — target: ${target}\n`)

  // Ensure output directory
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true })
  }

  // Compile all pages to static HTML
  const { dslRoutes } = await import("../app/routes")
  const pagesDir = path.join(outDir, "pages")
  if (!fs.existsSync(pagesDir)) {
    fs.mkdirSync(pagesDir, { recursive: true })
  }

  console.log(`Compiling ${dslRoutes.length} pages...`)
  const routeList: Array<{ path: string; label: string }> = []
  for (const route of dslRoutes) {
    const html = compilePage(route.page, {
      title: route.page.title,
      route: route.path,
    })
    const relPath = route.path.replace(/^\//, "") || "index"
    const outPath = path.join(pagesDir, `${relPath}.html`)
    const dir = path.dirname(outPath)
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(outPath, html, "utf-8")
    routeList.push({ path: route.path, label: route.label })
    console.log(`  ✓ ${route.key} → ${outPath}`)
  }

  // Bundle server
  console.log("\nBundling server...")
  const serverOutPath = path.join(outDir, "server.mjs")
  // Simple bundling: concatenate the server entry with the compiler
  const serverCode = `
// Declaro Server Bundle — generated by declaro deploy
import express from "express"
import { dslRoutes } from "./routes.mjs"
import { compilePage } from "./compiler.mjs"

const app = express()
const PORT = process.env.PORT ?? 3000

app.use(express.json())
app.use(express.urlencoded({ extended: true }))

// Pre-compile pages
const cache = new Map()
for (const route of dslRoutes) {
  cache.set(route.key, compilePage(route.page, { title: route.page.title, route: route.path }))
}

// Register routes
for (const route of dslRoutes) {
  app.get(route.path, (_req, res) => res.send(cache.get(route.key)))
}

app.get("/", (_req, res) => res.redirect(dslRoutes[0]?.path ?? "/"))

const port = process.env.PORT ?? 3000
app.listen(port, () => console.log(\`Declaro server: http://localhost:\${port}\`))
`.trim()

  fs.writeFileSync(serverOutPath, serverCode, "utf-8")
  console.log(`  ✓ Server bundle → ${serverOutPath}`)

  // Generate platform config
  const adapter = getAdapter(target)
  await adapter.generate(outDir, routeList)

  console.log(`\n✅ Deploy ready: ${outDir}/`)
  console.log(`   Target: ${target}`)
  console.log(`   Pages: ${dslRoutes.length}`)
}

function getAdapter(target: DeployTarget): DeployAdapter {
  switch (target) {
    case "vercel":
      return {
        name: "Vercel",
        generate: generateVercelConfig,
      }
    case "cloudflare":
      return {
        name: "Cloudflare Workers",
        generate: generateCloudflareConfig,
      }
    case "node":
    default:
      return {
        name: "Node.js (Docker)",
        generate: generateNodeConfig,
      }
  }
}

// ===== Vercel Adapter =====
async function generateVercelConfig(
  outDir: string,
  routes: Array<{ path: string; label: string }>,
): Promise<void> {
  // Generate vercel.json with serverless function
  const config = {
    version: 2,
    builds: [
      {
        src: "pages/**/*.html",
        use: "@vercel/static",
      },
      {
        src: "server.mjs",
        use: "@vercel/node",
      },
    ],
    routes: [
      // Static pages
      ...routes.map((r) => ({
        src: r.path,
        dest: `/pages${r.path === "/" ? "/index" : r.path}.html`,
      })),
      // API fallback
      { src: "/api/(.*)", dest: "/server.mjs" },
      // Root redirect
      { src: "/", dest: routes[0]?.path ?? "/pages/index.html" },
    ],
  }

  fs.writeFileSync(
    path.join(outDir, "vercel.json"),
    JSON.stringify(config, null, 2),
  )
  console.log("  ✓ vercel.json generated")
}

// ===== Cloudflare Workers Adapter =====
async function generateCloudflareConfig(
  outDir: string,
  routes: Array<{ path: string; label: string }>,
): Promise<void> {
  // wrangler.toml
  const wranglerConfig = `
name = "declaro-app"
compatibility_date = "2025-01-01"
main = "worker.mjs"

[site]
bucket = "./pages"
`.trim()

  fs.writeFileSync(path.join(outDir, "wrangler.toml"), wranglerConfig)
  console.log("  ✓ wrangler.toml generated")

  // Cloudflare Worker script for SSR
  const workerCode = `
// Declaro Cloudflare Worker
import { compilePage } from "./compiler.mjs"

// Pre-compiled routes (embedded at deploy time)
const ROUTES = ${JSON.stringify(routes)};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const route = ROUTES.find(r => r.path === url.pathname)

    if (route) {
      // Return pre-compiled page
      const pagePath = url.pathname === "/" ? "/index" : url.pathname
      const response = await env.ASSETS.fetch(new Request(\`/pages\${pagePath}.html\`, request))
      return response
    }

    return new Response("Not Found", { status: 404 })
  }
}
`.trim()

  fs.writeFileSync(path.join(outDir, "worker.mjs"), workerCode)
  console.log("  ✓ worker.mjs generated")
}

// ===== Node.js / Docker Adapter =====
async function generateNodeConfig(outDir: string, _routes: Array<{ path: string; label: string }>): Promise<void> {
  // Dockerfile
  const dockerfile = `
FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --production
COPY dist/ ./dist/
EXPOSE 3000
CMD ["node", "dist/server.mjs"]
`.trim()

  fs.writeFileSync(path.join(outDir, "Dockerfile"), dockerfile)
  console.log("  ✓ Dockerfile generated")

  // docker-compose.yml
  const compose = `
version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
`.trim()

  fs.writeFileSync(path.join(outDir, "docker-compose.yml"), compose)
  console.log("  ✓ docker-compose.yml generated")

  // .dockerignore
  fs.writeFileSync(
    path.join(outDir, ".dockerignore"),
    "node_modules\n.git\n*.md\n",
  )
  console.log("  ✓ .dockerignore generated")
}

// ===== CLI integration =====
export async function deployCommand(args: string[]): Promise<void> {
  const targetFlag = args.find((a) => a.startsWith("--target="))
  const target = (targetFlag?.split("=")[1] ?? "node") as DeployTarget
  const outDir = args.find((a) => !a.startsWith("--")) ?? "dist"

  if (!["node", "vercel", "cloudflare"].includes(target)) {
    console.error(`Error: Unknown target "${target}". Use: node, vercel, or cloudflare`)
    process.exit(1)
  }

  // Extract project name from package.json
  let projectName = "declaro-app"
  try {
    const pkg = JSON.parse(fs.readFileSync("package.json", "utf-8"))
    projectName = pkg.name ?? projectName
  } catch {
    // Use default
  }

  await deploy({ target, outDir, projectName })
}
