export * from "./core"
export * from "./env"
export * from "./page"
export * from "./component"
export * from "./actions"

export * from "./components/box"
export * from "./components/button"
export * from "./components/card"
export * from "./components/form"
export * from "./components/html"
export * from "./components/input"
export * from "./components/katex"
export * from "./components/list"
export * from "./components/modal"
export * from "./components/script"
export * from "./components/select"
export * from "./components/slider"
export * from "./components/table"
export * from "./components/text"
export * from "./components/textarea"
export * from "./components/island"

// Side-effect: register all built-in components in the plugin registry
import "./registerBuiltins"

export * from "./plugin"
export { registerBuiltinCompilers } from "./registerBuiltins"
